version: '3'
services:
  elasticsearch:
    build: ./elasticsearch

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password

  redis:
    image: redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password

  web:
    build: .
    command: rails s -b '0.0.0.0'
    volumes:
      - .:/myapp
    depends_on:
      - db
      - sidekiq
      - elasticsearch
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password