default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: pubdictionaries
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: pubdictionaries_test
  username: postgres
  password: password
  host: db

production:
  <<: *default
  database: pubdictionaries
