default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: pubdictionaries_dev

test:
  <<: *default
  database: pubdictionaries_test

production:
  <<: *default
  database: pubdictionaries
