development:
  adapter: postgresql
  encoding: utf8
  database: pubdictionaries
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: pubdictionaries_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: pubdictionaries
  pool: 5