development:
  adapter: postgresql
  encoding: utf8
  database: pubdictionaries_development

test:
  adapter: postgresql
  encoding: utf8
  database: pubdictionaries_test

production:
  adapter: postgresql
  encoding: utf8
  database: pubdictionaries

